services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://localhost:8000
      - CLIENT_URL=http://localhost:3000
    command: python app/main.py
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: npm run dev
    depends_on:
      - backend

